flyway.url=jdbc:sqlite:database.sqlite
flyway.locations=filesystem:migration
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.baselineDescription=Existing schema before Flyway migration
flyway.validateOnMigrate=true